const PRODUCTOS = [
    {
        id: 1,
        nombre: 'Mouse Gamer',
        descripcion: 'Mouse óptico RGB con 6 botones y luces LED.',
        precio: 25000,
        imagen: 'mouse.png',
        categoria: 'Periféricos',
    },
    {
        id: 2,
        nombre: 'Teclado Mecánico',
        descripcion: 'Teclado retroiluminado con switches azules.',
        precio: 65000,
        imagen: 'teclado.png',
        categoria: 'Periféricos',
    },
    {
        id: 3,
        nombre: 'Monitor 24"',
        descripcion: 'Monitor Full HD, 75Hz, panel IPS.',
        precio: 125000,
        imagen: 'monitor.jpg',
        categoria: 'Monitores',
    },
    {
        id: 4,
        nombre: 'Notebook 14"',
        descripcion: 'Intel i5, 8GB RAM, SSD 256GB.',
        precio: 120000,
        imagen: 'note.png',
        categoria: 'Computadoras',
    },
    {
        id: 5,
        nombre: 'Auriculares',
        descripcion: 'Auriculares con micrófono y cancelación de ruido.',
        precio: 40000,
        imagen: 'auriculares.jpg',
        categoria: 'Periféricos',
    },
    {
        id: 6,
        nombre: 'PC Escritorio',
        descripcion: 'Ryzen 5, 16GB RAM, SSD 512GB.',
        precio: 180000,
        imagen: 'pces.webp',
        categoria: 'Computadoras',
    },
];